# -*- coding: utf-8 -*-
"""202401100700118_B.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zrYcmDPwV9FsNssN3B2KLSy2JigpoEuK

# Grocery store calculator
"""

a=int(input("Enter no of items"))
total_cost=0
for x in range(a):
  N=input("Enter product name")
  A=float(input("price of item"))
  B=int(input("enter the quantity"))
  item_cost=A*B
  print(item_cost)
  total_cost=total_cost+item_cost
  print(total_cost)