# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dHclDTjnLpKhj_pjx-rhwwK1Is7aVB0j
"""

import matplotlib.pyplot as plt
import numpy as np

# Initialize brightness level (0 to 1)
brightness = 0.5

# RGB value for LED
color = (1, 0, 0)  # Red LED

def draw_led(brightness):
    plt.clf()
    plt.xlim(-1, 1)
    plt.ylim(-1, 1)
    plt.axis('off')
    plt.gca().set_facecolor((0, 0, 0))  # Black background
    circle = plt.Circle((0, 0), 0.5, color=(color[0] * brightness,
                                              color[1] * brightness,
                                              color[2] * brightness))
    plt.gca().add_patch(circle)
    plt.pause(0.1)  # Pause to update the plot

# Set up the plot
plt.ion()  # Turn on interactive mode
plt.figure(figsize=(3, 3))

# Display initial state
draw_led(brightness)

while True:
    user_input = input("Increase (+), Decrease (-), Exit (q): ").strip().lower()
    if user_input == '+':
        brightness = min(1, brightness + 0.1)  # Increase brightness
    elif user_input == '-':
        brightness = max(0, brightness - 0.1)  # Decrease brightness
    elif user_input == 'q':
        break  # Exit the loop

    draw_led(brightness)

# Turn off interactive mode
plt.ioff()
plt.show()